### ISSUE TITLE
Block code starting with 4 spaces cannot be rendered when used with CodeRayify

### ISSUE THREAD

**Issue by serv** [vmg/redcarpet#308]
``` ruby
code = "    puts 'hello word'"

class CodeRayify < Redcarpet::Render::HTML
  def block_code(code, language)
    CodeRay.scan(code, language).div
  end
end

def markdown(text)
  coderayified = CodeRayify.new(:filter_html => true, 
                                :hard_wrap => true)
  options = {
    :fenced_code_blocks => true,
    :no_intra_emphasis => true,
    :autolink => true,
    :strikethrough => true,
    :lax_html_blocks => true,
    :superscript => true
  }
  markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
  debugger
  markdown_to_html.render(text).html_safe
end

markdown(code)
```

`markdown_to_html.render(text)` part returns this error.

`*** ArgumentError Exception: Symbol or String expected, but NilClass given.`

Any thoughts on this?

**Comment by ldco2016** [comment]
Greetings, I have come upon a similar issue with similar code:

```
module BlogsHelper
	def gravatar_helper user
		image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 60
	end

	class CodeRayify < Redcarpet::Render::HTML
		def block_code(code, language)
			CodeRay.scan(code, language).div
		end
	end

	def markdown(text)
		coderayify = CodeRayify.new(filter_html: true, hard_wrap: true)

		options = {
			fenced_code_blocks: true,
			no_intra_emphasis: true,
			autolink: true,
			lax_html_blocks: true,
		}

		markdown_to_html = Redcarpet::Markdown.new(coderayify, options)
		markdown_to_html.render(text).html_safe
	end

	def blog_status_color blog
		'color: red;' if blog.draft?
	end
end

```

The difference is my error in the logs say:

```
ActionView::Template::Error (Symbol or String expected, but NilClass given.):
2017-11-21T19:04:10.635079+00:00 app[web.1]: F, [2017-11-21T19:04:10.635014 #4] FATAL -- : [9091d983-bc39-4f64-b86e-c388e3893072]     4:
2017-11-21T19:04:10.635081+00:00 app[web.1]: [9091d983-bc39-4f64-b86e-c388e3893072]     5:     <%= render partial: 'blogs/admin_actions', locals: {blog: blog} %>
2017-11-21T19:04:10.635082+00:00 app[web.1]: [9091d983-bc39-4f64-b86e-c388e3893072]     6:
2017-11-21T19:04:10.635083+00:00 app[web.1]: [9091d983-bc39-4f64-b86e-c388e3893072]     7:     <p><%= markdown blog.body %></p>
2017-11-21T19:04:10.635083+00:00 app[web.1]: [9091d983-bc39-4f64-b86e-c388e3893072]     8:
2017-11-21T19:04:10.635084+00:00 app[web.1]: [9091d983-bc39-4f64-b86e-c388e3893072]     9:  </div><!-- /.blog-post -->
2017-11-21T19:04:10.635166+00:00 app[web.1]: F, [2017-11-21T19:04:10.635106 #4] FATAL -- : [9091d983-bc39-4f64-b86e-c388e3893072]
2017-11-21T19:04:10.635268+00:00 app[web.1]: F, [2017-11-21T19:04:10.635198 #4] FATAL -- : [9091d983-bc39-4f64-b86e-c388e3893072] app/helpers/blogs_helper.rb:8:in `block_code'
2017-11-21T19:04:10.635270+00:00 app[web.1]: [9091d983-bc39-4f64-b86e-c388e3893072] app/helpers/blogs_helper.rb:23:in `render'
2017-11-21T19:04:10.635271+00:00 app[web.1]: [9091d983-bc39-4f64-b86e-c388e3893072] app/helpers/blogs_helper.rb:23:in `markdown'
```
Any guidance on what is going on here is appreciated.
