### ISSUE TITLE
Seg fault when trying to render TOC

### ISSUE THREAD

**Issue by sapslaj** [vmg/redcarpet#494]
I was doing some benchmarks and I keep getting segfaulted when doing HTML_TOC rendering

Here's my benchmark code:
```ruby 
require 'benchmark/ips'
require 'redcarpet.so'

TESTMD = File.read("./markdown_test_data.md") # from https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

# Warmups
Redcarpet::Markdown.new(Redcarpet::Render::HTML.new).render(TESTMD)
Redcarpet::Markdown.new(Redcarpet::Render::HTML_TOC.new).render(TESTMD)

Benchmark.ips do |x|
  x.report 'standard-redcarpet' do
    Redcarpet::Markdown.new(Redcarpet::Render::HTML.new).render(TESTMD)
  end

  x.report 'standard-redcarpet-toc' do
    Redcarpet::Markdown.new(Redcarpet::Render::HTML_TOC.new).render(TESTMD)
  end
end

```

Output on Windows
```
D:\benchmarks $ ruby markdown_benchmark.rb
Calculating -------------------------------------
  standard-redcarpet   468.000  i/100ms
standard-redcarpet-toc
                       630.000  i/100ms
-------------------------------------------------
  standard-redcarpetC:/Rubies/Ruby22/lib/ruby/gems/2.2.0/gems/benchmark-ips-2.2.0/lib/benchmark/ips.rb:90: [BUG] Segmentation fault
ruby 2.2.1p85 (2015-02-26 revision 49769) [i386-mingw32]

-- Control frame information -----------------------------------------------
c:0009 p:---- s:0054 e:000053 CFUNC  :%
c:0008 p:0135 s:0050 e:000049 METHOD C:/Rubies/Ruby22/lib/ruby/gems/2.2.0/gems/benchmark-ips-2.2.0/lib/benchmark/ips.rb:90
c:0007 p:0114 s:0044 e:000042 METHOD C:/Rubies/Ruby22/lib/ruby/gems/2.2.0/gems/benchmark-ips-2.2.0/lib/benchmark/ips/report.rb:81
c:0006 p:0328 s:0038 e:000035 BLOCK  C:/Rubies/Ruby22/lib/ruby/gems/2.2.0/gems/benchmark-ips-2.2.0/lib/benchmark/ips/job.rb:308 [FINISH]
c:0005 p:---- s:0020 e:000019 CFUNC  :each
c:0004 p:0009 s:0017 e:000016 METHOD C:/Rubies/Ruby22/lib/ruby/gems/2.2.0/gems/benchmark-ips-2.2.0/lib/benchmark/ips/job.rb:258
c:0003 p:0229 s:0014 e:000013 METHOD C:/Rubies/Ruby22/lib/ruby/gems/2.2.0/gems/benchmark-ips-2.2.0/lib/benchmark/ips.rb:53
c:0002 p:0116 s:0004 E:001bbc EVAL   markdown_benchmark.rb:10 [FINISH]
c:0001 p:0000 s:0002 E:0020ec TOP    [FINISH]

-- Ruby level backtrace information ----------------------------------------
markdown_benchmark.rb:10:in `<main>'
C:/Rubies/Ruby22/lib/ruby/gems/2.2.0/gems/benchmark-ips-2.2.0/lib/benchmark/ips.rb:53:in `ips'
C:/Rubies/Ruby22/lib/ruby/gems/2.2.0/gems/benchmark-ips-2.2.0/lib/benchmark/ips/job.rb:258:in `run'
C:/Rubies/Ruby22/lib/ruby/gems/2.2.0/gems/benchmark-ips-2.2.0/lib/benchmark/ips/job.rb:258:in `each'
C:/Rubies/Ruby22/lib/ruby/gems/2.2.0/gems/benchmark-ips-2.2.0/lib/benchmark/ips/job.rb:308:in `block in run'
C:/Rubies/Ruby22/lib/ruby/gems/2.2.0/gems/benchmark-ips-2.2.0/lib/benchmark/ips/report.rb:81:in `body'
C:/Rubies/Ruby22/lib/ruby/gems/2.2.0/gems/benchmark-ips-2.2.0/lib/benchmark/ips.rb:90:in `scale'
C:/Rubies/Ruby22/lib/ruby/gems/2.2.0/gems/benchmark-ips-2.2.0/lib/benchmark/ips.rb:90:in `%'

-- C level backtrace information -------------------------------------------
C:\WINDOWS\SYSTEM32\ntdll.dll(NtWaitForSingleObject+0xc) [0x77E6512C]
C:\WINDOWS\SYSTEM32\KERNELBASE.dll(WaitForSingleObject+0x12) [0x754C1802]
C:\Rubies\Ruby22\bin\msvcrt-ruby220.dll(rb_vm_bugreport+0xa7) [0x640D4307]
C:\Rubies\Ruby22\bin\msvcrt-ruby220.dll(rb_bug_context+0x42) [0x63F86A22]
C:\Rubies\Ruby22\bin\msvcrt-ruby220.dll(rb_check_safe_obj+0x394) [0x6404F4A4]
 [0x00401866]
C:\WINDOWS\SYSTEM32\ntdll.dll(WinSqmEventWrite+0x1c795) [0x77E96805]

-- Other runtime information -----------------------------------------------

* Loaded script: markdown_benchmark.rb

* Loaded features:

    0 enumerator.so
    1 rational.so
    2 complex.so
    3 C:/Rubies/Ruby22/lib/ruby/2.2.0/i386-mingw32/enc/encdb.so
    4 C:/Rubies/Ruby22/lib/ruby/2.2.0/i386-mingw32/enc/trans/transdb.so
    5 C:/Rubies/Ruby22/lib/ruby/2.2.0/i386-mingw32/enc/iso_8859_1.so
    6 C:/Rubies/Ruby22/lib/ruby/2.2.0/unicode_normalize.rb
    7 C:/Rubies/Ruby22/lib/ruby/2.2.0/i386-mingw32/rbconfig.rb
    8 thread.rb
    9 C:/Rubies/Ruby22/lib/ruby/2.2.0/i386-mingw32/thread.so
   10 C:/Rubies/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/compatibility.rb
   11 C:/Rubies/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/defaults.rb
   12 C:/Rubies/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/deprecate.rb
   13 C:/Rubies/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/errors.rb
   14 C:/Rubies/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/version.rb
   15 C:/Rubies/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/requirement.rb
   16 C:/Rubies/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/platform.rb
   17 C:/Rubies/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb
   18 C:/Rubies/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/stub_specification.rb
   19 C:/Rubies/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/util/stringio.rb
   20 C:/Rubies/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb
   21 C:/Rubies/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/exceptions.rb
   22 C:/Rubies/Ruby22/lib/ruby/2.2.0/rubygems/defaults/operating_system.rb
   23 C:/Rubies/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb
   24 C:/Rubies/Ruby22/lib/ruby/2.2.0/monitor.rb
   25 C:/Rubies/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb
   26 C:/Rubies/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems.rb
   27 C:/Rubies/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/path_support.rb
   28 C:/Rubies/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb
   29 C:/Rubies/Ruby22/lib/ruby/gems/2.2.0/gems/benchmark-ips-2.2.0/lib/benchmark/timing.rb
   30 C:/Rubies/Ruby22/lib/ruby/gems/2.2.0/gems/benchmark-ips-2.2.0/lib/benchmark/compare.rb
   31 C:/Rubies/Ruby22/lib/ruby/gems/2.2.0/gems/benchmark-ips-2.2.0/lib/benchmark/ips/report.rb
   32 C:/Rubies/Ruby22/lib/ruby/gems/2.2.0/gems/benchmark-ips-2.2.0/lib/benchmark/ips/job.rb
   33 C:/Rubies/Ruby22/lib/ruby/gems/2.2.0/gems/benchmark-ips-2.2.0/lib/benchmark/ips.rb
   34 C:/Rubies/Ruby22/lib/ruby/gems/2.2.0/gems/redcarpet-3.3.1/lib/redcarpet.so

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html


This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

D:\benchmarks $
```

Output on Linux:
```
[sapslaj@boxxy benchmarks ]$ ruby markdown_benchmark.rb
Calculating -------------------------------------
  standard-redcarpet*** Error in `ruby': free(): invalid pointer: 0x08d6ded8 ***
[1]    3966 abort (core dumped)  ruby markdown_benchmark.rb
[sapslaj@boxxy benchmarks ]$ ruby -v
ruby 2.1.1p76 (2014-02-24 revision 45161) [i686-linux]
```

**Comment by adriaanm** [comment]
Same here: 
  - broken (on 3.3, also tried 3.3.1): https://travis-ci.org/scala/scala/builds/65747400
  - fixed (pin to 3.2.3): https://travis-ci.org/scala/scala/builds/67595824

**Comment by SethTisue** [comment]
as a postscript to @adriaanm's comment, we aren't actually sure this is really the "same" crash as @sapslaj's. if it would be helpful for me to attempt to minimize the input that makes it fail, let me know. I wasn't able to reproduce the crash locally on OS X, but it happened every time running on Travis-CI under Ubuntu.

**Comment by sapslaj** [comment]
Update: I did a bit more testing and you will never believe this. 

I made a script that runs `Redcarpet::Markdown.new(Redcarpet::Render::HTML_TOC.new).render(TESTMD)` 10,000 times.

On Linux, the bit that is making it crash is this:
```
<a name="code"/>
## Code and Syntax Highlighting
```

```
$ ruby markdown_benchmark_before_newline.rb

2*** Error in `ruby': free(): invalid next size (fast): 0x09eb7f00 ***
[1]    19214 abort (core dumped)  ruby markdown_benchmark.rb
```

Now the really funny bit. Add a space between those two lines in the markdown:
```
<a name="code"/>

## Code and Syntax Highlighting
```

Completely different crash:
```
$ ruby markdown_benchmark_after_newline.rb

97ruby: malloc.c:2372: sysmalloc: Assertion `(old_top == (((mbinptr) (((char *) &((av)->bins[((1) - 1) * 2])) - __builtin_offsetof (struct malloc_chunk, fd)))) && old_size == 0) || ((unsigned long) (old_size) >= (unsigned long)((((__builtin_offsetof (struct malloc_chunk, fd_nextsize))+((2 *(sizeof(size_t))) - 1)) & ~((2 *(sizeof(size_t))) - 1))) && ((old_top)->size & 0x1) && ((unsigned long) old_end & pagemask) == 0)' failed.
[1]    19222 abort (core dumped)  ruby markdown_benchmark.rb
```

The really funny bit: Both of these tests work flawlessly on Windows. 
```
D:\benchmarks $ ruby markdown_benchmark_before_newline.rb

9999
D:\benchmarks $ ruby markdown_benchmark_after_newline.rb

9999
D:\benchmarks $
```

I should note that the normal HTML renderer does not crash when running these tests. 

So I said screw it. Let's throw the whole [test data](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) in and see what happens. Now for the *even funnier* bit. 

On Linux, crashes like normal. On Windows, however, it goes through a seemingly random number of iterations before crashing.
```
D:\benchmarks $ ruby markdown_benchmark.rb

3001markdown_benchmark.rb:7: [BUG] Segmentation fault
ruby 2.2.1p85 (2015-02-26 revision 49769) [i386-mingw32]
...
```

And to top it off, **sometimes** when it crashes it will get stuck on writing the C backtrace, and if I kill one of the two (only has two processes sometimes?) Ruby interpreter in Task Manager, **sometimes** it will continue going, but **most** of the time it spits out the backtrace and exits. 

This is very erratic behavior and it only seems to happen to the HTML_TOC renderer. I suppose since it's derived from the HTML renderer it could be a bug in either. I'll try to do some more testing with OS X later tonight or tomorrow and I'll keep you updated. But as for now, 
![I can't even](http://i.imgur.com/nAlo6Fv.jpg)

**Comment by robin850** [comment]
Hi there!

This looks like

**Comment by sapslaj** [comment]
Yep. Tests are passing now. Looks like 3.3.2 fixed the issue.

**Comment by robin850** [comment]
Awesome! Thanks for confirming and sorry for the late answer! :heart:
