### ISSUE TITLE
Symbol Not Found on Apple Silicon

### ISSUE THREAD

**Issue by kevinchau** [vmg/redcarpet#698]
Have tried different ways of installing the gem, but it's still failing to run:

```
kevinchau@MacBook-Pro radioapp-ios % arch -x86_64 redcarpet -v              
Traceback (most recent call last):
	10: from /usr/local/bin/redcarpet:23:in `<main>'
	 9: from /usr/local/bin/redcarpet:23:in `load'
	 8: from /Users/kevinchau/.gem/ruby/2.6.0/gems/redcarpet-3.5.0/bin/redcarpet:5:in `<top (required)>'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /Users/kevinchau/.gem/ruby/2.6.0/gems/redcarpet-3.5.0/lib/redcarpet/cli.rb:1:in `<top (required)>'
	 4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /Users/kevinchau/.gem/ruby/2.6.0/gems/redcarpet-3.5.0/lib/redcarpet.rb:1:in `<top (required)>'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlsym(0x7f963060cee0, Init_redcarpet): symbol not found - /Users/kevinchau/.gem/ruby/2.6.0/gems/redcarpet-3.5.0/lib/redcarpet.bundle (LoadError)
```

**Comment by robin850** [comment]
Hello,

Sorry for the late reply. I don't have any access to an Apple computer with an M1 chip to debug such problem at the moment. Are you able to deal with any other native gem with success such as ffi or nokogiri ?

**Comment by kevinchau** [comment]
Unfortunately I haven't done a lot of look into it. I managed to get it to work under Rosetta and have been doing that for now. I am more than happy to test if things can run natively on Apple Silicon, but that would be the extent of my knowledge on Ruby.
